public enum ResearchEntryID
{
    None = -1,
    ADP_ATP = 1,
    Centrosome = 2,
    CytoplasmicProteins = 3,
    Dynein = 4,
    ElectronTransportChain = 5,
    Electrons = 6,
    ERProteins = 7,
    GolgiApparatus = 8,
    Kinesin = 9,
    Membrane = 10,
    Microtubule = 11,
    Mitochondria = 12,
    MitochondrialDNA = 13,
    MitochondrialProteins = 14,
    Nucleus = 15,
    Protons = 16,
    RoughER = 17,
    SmoothER = 18,
    Vesicle = 19,
    Ribosome = 20,
}
